const translatorLanguages = [
	{ code: "af", language: "Afrikaans", nativeName: "Afrikaans" },
	{ code: "ar", language: "Arabic", nativeName: "العربية" },
	{ code: "as", language: "Assamese", nativeName: "Assamese" },
	{ code: "bg", language: "Bulgarian", nativeName: "Български" },
	{ code: "bn", language: "Bangla", nativeName: "বাংলা" },
	{
		code: "bs",
		language: "Bosnian",
		nativeName: "bosanski (latinica)"
	},
	{ code: "ca", language: "Catalan", nativeName: "Català" },
	{ code: "cs", language: "Czech", nativeName: "Čeština" },
	{ code: "cy", language: "Welsh", nativeName: "Welsh" },
	{ code: "da", language: "Danish", nativeName: "Dansk" },
	{ code: "de", language: "German", nativeName: "Deutsch" },
	{ code: "el", language: "Greek", nativeName: "Ελληνικά" },
	{ code: "en", language: "English", nativeName: "English" },
	{ code: "es", language: "Spanish", nativeName: "Español" },
	{ code: "et", language: "Estonian", nativeName: "Eesti" },
	{ code: "fa", language: "Persian", nativeName: "Persian" },
	{ code: "fi", language: "Finnish", nativeName: "Suomi" },
	{ code: "fil", language: "Filipino", nativeName: "Filipino" },
	{ code: "fj", language: "Fijian", nativeName: "Fijian" },
	{ code: "fr", language: "French", nativeName: "Français" },
	{
		code: "fr-ca",
		language: "French (Canada)",
		nativeName: "French (Canada)"
	},
	{ code: "ga", language: "Irish", nativeName: "Gaeilge" },
	{ code: "gu", language: "Gujarati", nativeName: "ગુજરાતી" },
	{ code: "he", language: "Hebrew", nativeName: "עברית" },
	{ code: "hi", language: "Hindi", nativeName: "हिंदी" },
	{ code: "hr", language: "Croatian", nativeName: "Hrvatski" },
	{
		code: "ht",
		language: "Haitian Creole",
		nativeName: "Haitian Creole"
	},
	{ code: "hu", language: "Hungarian", nativeName: "Magyar" },
	{ code: "id", language: "Indonesian", nativeName: "Indonesia" },
	{ code: "is", language: "Icelandic", nativeName: "Íslenska" },
	{ code: "it", language: "Italian", nativeName: "Italiano" },
	{ code: "ja", language: "Japanese", nativeName: "日本語" },
	{ code: "kk", language: "Kazakh", nativeName: "Kazakh" },
	{
		code: "kmr",
		language: "Kurdish (Northern)",
		nativeName: "Kurdish (Northern)"
	},
	{ code: "kn", language: "Kannada", nativeName: "ಕನ್ನಡ" },
	{ code: "ko", language: "Korean", nativeName: "한국어" },
	{
		code: "ku",
		language: "Kurdish (Central)",
		nativeName: "Kurdish (Central)"
	},
	{ code: "lt", language: "Lithuanian", nativeName: "Lietuvių" },
	{ code: "lv", language: "Latvian", nativeName: "Latviešu" },
	{ code: "mg", language: "Malagasy", nativeName: "Malagasy" },
	{ code: "mi", language: "Maori", nativeName: "Māori" },
	{ code: "ml", language: "Malayalam", nativeName: "മലയാളം" },
	{ code: "mr", language: "Marathi", nativeName: "मराठी" },
	{ code: "ms", language: "Malay", nativeName: "Melayu" },
	{ code: "mt", language: "Maltese", nativeName: "Il-Malti" },
	{ code: "mww", language: "Hmong Daw", nativeName: "Hmong Daw" },
	{ code: "nb", language: "Norwegian", nativeName: "Norsk" },
	{ code: "nl", language: "Dutch", nativeName: "Nederlands" },
	{ code: "or", language: "Odia", nativeName: "Odia" },
	{
		code: "otq",
		language: "Querétaro Otomi",
		nativeName: "Querétaro Otomi"
	},
	{ code: "pa", language: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
	{ code: "pl", language: "Polish", nativeName: "Polski" },
	{ code: "prs", language: "Dari", nativeName: "Dari" },
	{ code: "ps", language: "Pashto", nativeName: "Pashto" },
	{
		code: "pt",
		language: "Portuguese (Brazil)",
		nativeName: "Português (Brasil)"
	},
	{
		code: "pt-pt",
		language: "Portuguese (Portugal)",
		nativeName: "Português (Portugal)"
	},
	{ code: "ro", language: "Romanian", nativeName: "Română" },
	{ code: "ru", language: "Russian", nativeName: "Русский" },
	{ code: "sk", language: "Slovak", nativeName: "Slovenčina" },
	{ code: "sl", language: "Slovenian", nativeName: "Slovenščina" },
	{ code: "sm", language: "Samoan", nativeName: "Samoan" },
	{
		code: "sr-Cyrl",
		language: "Serbian (Cyrillic)",
		nativeName: "srpski (ćirilica)"
	},
	{
		code: "sr-Latn",
		language: "Serbian (Latin)",
		nativeName: "srpski (latinica)"
	},
	{ code: "sv", language: "Swedish", nativeName: "Svenska" },
	{ code: "sw", language: "Swahili", nativeName: "Kiswahili" },
	{ code: "ta", language: "Tamil", nativeName: "தமிழ்" },
	{ code: "te", language: "Telugu", nativeName: "తెలుగు" },
	{ code: "th", language: "Thai", nativeName: "ไทย" },
	{
		code: "tlh-Latn",
		language: "Klingon (Latin)",
		nativeName: "Klingon (Latin)"
	},
	{
		code: "tlh-Piqd",
		language: "Klingon (pIqaD)",
		nativeName: "Klingon (pIqaD)"
	},
	{ code: "to", language: "Tongan", nativeName: "lea fakatonga" },
	{ code: "tr", language: "Turkish", nativeName: "Türkçe" },
	{ code: "ty", language: "Tahitian", nativeName: "Tahitian" },
	{ code: "uk", language: "Ukrainian", nativeName: "Українська" },
	{ code: "ur", language: "Urdu", nativeName: "اردو" },
	{ code: "vi", language: "Vietnamese", nativeName: "Tiếng Việt" },
	{ code: "yua", language: "Yucatec Maya", nativeName: "Yucatec Maya" },
	{
		code: "yue",
		language: "Cantonese (Traditional)",
		nativeName: "粵語 (繁體中文)"
	},
	{
		code: "zh-Hans",
		language: "Chinese Simplified",
		nativeName: "简体中文"
	},
	{
		code: "zh-Hant",
		language: "Chinese Traditional",
		nativeName: "繁體中文"
	}
];

const signUp = [
	{ af: "Teken in" },
	{ ar: "التسجيل" },
	{ as: "ছাই আপ" },
	{ bg: "Регистрирайте се" },
	{ bn: "সাইন আপ করো" },
	{ bs: "Prijavi se" },
	{ ca: "Inscriure" },
	{ cs: "Registrace" },
	{ cy: "Ymuno" },
	{ da: "Tilmeld dig" },
	{ de: "Anmelden" },
	{ el: "Εγγραφή" },
	{ en: "Sign up" },
	{ es: "Únete" },
	{ et: "Pane nimi kirja" },
	{ fa: "ثبت نام" },
	{ fi: "Kiinnittää" },
	{ fil: "Mag-sign up" },
	{ fj: "Curuiloma" },
	{ fr: "s'enregistrer" },
	{ "fr-CA": "S'inscrire" },
	{ ga: "Cláraigh" },
	{ gu: "સાઇન અપ કરો" },
	{ he: "הירשם" },
	{ hi: "नाम लिखो" },
	{ hr: "Prijavi se" },
	{ ht: "enskri" },
	{ hu: "feliratkozni" },
	{ id: "Tandatangan" },
	{ is: "Skrá sig" },
	{ it: "Registrati" },
	{ ja: "サインアップ" },
	{ kk: "Тіркелу" },
	{ kmr: "Tomar kirin" },
	{ kn: "ಸೈನ್ ಅಪ್ ಮಾಡಿ" },
	{ ko: "등록하세요" },
	{ ku: "خۆ تۆمارکردن" },
	{ lt: "užsiregistruoti, užsiregistruok" },
	{ lv: "piedalīties" },
	{ mg: "Midira" },
	{ mi: "Takiuru" },
	{ ml: "സൈൻ അപ്പ് ചെയ്യുക" },
	{ mr: "साइन अप करा" },
	{ ms: "Mendaftar" },
	{ mt: "Iffirma" },
	{ mww: "Cuv npe" },
	{ nb: "melde seg på" },
	{ nl: "Inschrijven" },
	{ or: "ସାଇନ୍‌ ଅପ୍‌" },
	{ otq: "Di unir" },
	{ pa: "ਸਾਈਨ ਅੱਪ ਕਰੋ" },
	{ pl: "Zarejestruj się" },
	{ prs: "ثبت نام" },
	{ ps: "ګډون وکړه" },
	{ pt: "Inscrição" },
	{ "pt-PT": "Registar-me" },
	{ ro: "înscrie-te" },
	{ ru: "Регистрация" },
	{ sk: "zaregistrovať sa" },
	{ sl: "prijava" },
	{ sm: "Saini e alu i luga" },
	{ "sr-Cyrl": "Пријави се" },
	{ "sr-Latn": "Prijavi se" },
	{ sv: "Registrera sig" },
	{ sw: "Jisajili" },
	{ ta: "பதிவுபெறு" },
	{ te: "సైన్ అప్" },
	{ th: "ไซน์อัพ" },
	{ "tlh-Latn": "bIjatlh 'e' yImev" },
	{ "tlh-Piqd": "  " },
	{ to: "Hu ki ʻolunga" },
	{ tr: "Kaydol" },
	{ ty: "Tapao i nia" },
	{ uk: "Зареєструватися" },
	{ ur: "سائن اپ" },
	{ vi: "Đăng ký" },
	{ yua: "Nuup'abáa" },
	{ yue: "登記" },
	{ "zh-Hans": "登记" },
	{ "zh-Hant": "登記" }
];

const welcome = [
	{ af: "Welkom" },
	{ ar: "أهلًا وسهلًا" },
	{ as: "স্বাগতম।" },
	{ bg: "Добре дошъл" },
	{ bn: "স্বাগতম।" },
	{ bs: "Dobrodošli" },
	{ ca: "Benvingut" },
	{ cs: "Vítejte" },
	{ cy: "Croesawu" },
	{ da: "Velkommen" },
	{ de: "Willkommen" },
	{ el: "Καλώς ήρθες" },
	{ en: "Welcome" },
	{ es: "Bienvenido" },
	{ et: "Tere tulemast" },
	{ fa: "خوش آمدید" },
	{ fi: "Tervetuloa" },
	{ fil: "Maligayang pagdating" },
	{ fj: "Ni Matavinaka mai" },
	{ fr: "Bienvenue" },
	{ "fr-CA": "Je vous souhaite la bienvenue" },
	{ ga: "Fáilte" },
	{ gu: "સ્વાગત છે" },
	{ he: "ברוך הבא" },
	{ hi: "स्वागत है।" },
	{ hr: "Dobrodošao" },
	{ ht: "Byenvini" },
	{ hu: "Isten hozott" },
	{ id: "Selamat datang" },
	{ is: "Velkominn" },
	{ it: "Benvenuto" },
	{ ja: "ようこそ" },
	{ kk: "Қош келдіңіз" },
	{ kmr: "Bi xêr hatî" },
	{ kn: "ಸ್ವಾಗತ" },
	{ ko: "환영" },
	{ ku: "بەخێربێیت" },
	{ lt: "sveikas atvykęs" },
	{ lv: "laipni lūdzam" },
	{ mg: "Tonga soa" },
	{ mi: "Nau mai" },
	{ ml: "സ്വാഗതം" },
	{ mr: "स्वागत आहे" },
	{ ms: "Selamat datang" },
	{ mt: "Merħba" },
	{ mww: "Zoo siab tos txais" },
	{ nb: "velkommen" },
	{ nl: "Welkom" },
	{ or: "ସ୍ୱାଗତମ୍‌।" },
	{ otq: "Hogu̲ntso̲ho̲" },
	{ pa: "ਸਵਾਗਤ ਹੈ।" },
	{ pl: "Zapraszamy" },
	{ prs: "خوش آمدید" },
	{ ps: "ښه راغلاست " },
	{ pt: "Bem-vindo" },
	{ "pt-PT": "Bem-vindos" },
	{ ro: "bun venit" },
	{ ru: "Приветствовать" },
	{ sk: "vitaj" },
	{ sl: "dobrodošli" },
	{ sm: "Susu maia" },
	{ "sr-Cyrl": "Добродољли" },
	{ "sr-Latn": "Dobrodoљli" },
	{ sv: "Välkommen" },
	{ sw: "Karibu" },
	{ ta: "வருக" },
	{ te: "స్వాగతం" },
	{ th: "ยินดี ต้อน รับ สู่" },
	{ "tlh-Latn": "yI'el" },
	{ "tlh-Piqd": "" },
	{ to: "Mālō e lelei" },
	{ tr: "Hoş geldi -niz" },
	{ ty: "Manava" },
	{ uk: "Прошу" },
	{ ur: "خوش آمدید" },
	{ vi: "Chào mừng" },
	{ yua: "Máanen" },
	{ yue: "歡迎" },
	{ "zh-Hans": "欢迎" },
	{ "zh-Hant": "歡迎" }
];

const login = [
	{ af: "Aanteken" },
	{ ar: "تسجيل الدخول" },
	{ as: "লগিন" },
	{ bg: "Вход" },
	{ bn: "লগইন" },
	{ bs: "Prijava" },
	{ ca: "Connexió" },
	{ cs: "Přihlášení" },
	{ cy: "Mewngofnodi" },
	{ da: "Login" },
	{ de: "einloggen" },
	{ el: "Σύνδεση" },
	{ en: "Login" },
	{ es: "Iniciar sesión" },
	{ et: "Login" },
	{ fa: "ورود" },
	{ fi: "Kirjaudu" },
	{ fil: "Mag-login" },
	{ fj: "Curu" },
	{ fr: "connectez-vous" },
	{ "fr-CA": "Connexion à l’écran" },
	{ ga: "Logáil isteach" },
	{ gu: "પ્રવેશ" },
	{ he: "כניסה" },
	{ hi: "लॉगिन" },
	{ hr: "Prijava" },
	{ ht: "Login" },
	{ hu: "Logika" },
	{ id: "Login" },
	{ is: "Tenging" },
	{ it: "Login" },
	{ ja: "ログイン" },
	{ kk: "Жүйеге кіру" },
	{ kmr: "Têbinî" },
	{ kn: "ಲಾಗಿನ್" },
	{ ko: "로그인" },
	{ ku: "چوونەژوورەوە" },
	{ lt: "Prisijungti" },
	{ lv: "Pieteikšanās" },
	{ mg: "Teny fidirana" },
	{ mi: "Takiuru" },
	{ ml: "ലോഗിൻ" },
	{ mr: "दाखलन" },
	{ ms: "Log masuk" },
	{ mt: "Illoggja" },
	{ mww: "ntxaij" },
	{ nb: "Pålogging" },
	{ nl: "Login" },
	{ or: "ଲଗଇନ" },
	{ otq: "Da du'mi ya sesión" },
	{ pa: "ਲਾਗਇਨ" },
	{ pl: "Logowania" },
	{ prs: "ورود" },
	{ ps: "د افغانستان د ټولو خلکو د راکړې" },
	{ pt: "Login" },
	{ "pt-PT": "Login" },
	{ ro: "Login" },
	{ ru: "Входа" },
	{ sk: "Prihlásiť" },
	{ sl: "Prijavo" },
	{ sm: "Alu i totonu" },
	{ "sr-Cyrl": "Пријављивање" },
	{ "sr-Latn": "Prijavljivanje" },
	{ sv: "Logga in" },
	{ sw: "Kuingia" },
	{ ta: "உள்நுழைவு" },
	{ te: "లాగిన్" },
	{ th: "เข้า สู่ ระบบ" },
	{ "tlh-Latn": "QonoS" },
	{ "tlh-Piqd": "" },
	{ to: "Login" },
	{ tr: "Oturum açma" },
	{ ty: "Login" },
	{ uk: "Логін" },
	{ ur: "لاگ ان" },
	{ vi: "Đăng nhập" },
	{ yua: "Máaxo'ob xoknáalo'obo'" },
	{ yue: "登錄" },
	{ "zh-Hans": "登录" },
	{ "zh-Hant": "登錄" }
];

const submit = [
	{ af: "Dien in" },
	{ ar: "إرسال" },
	{ as: "দাখিল কৰা" },
	{ bg: "Представят" },
	{ bn: "জমা" },
	{ bs: "Podaši" },
	{ ca: "Enviar" },
	{ cs: "Odeslat" },
	{ cy: "Cynnig" },
	{ da: "Indsende" },
	{ de: "Senden" },
	{ el: "Υποβάλει" },
	{ en: "Submit" },
	{ es: "Enviar" },
	{ et: "Esitada" },
	{ fa: "ارسال" },
	{ fi: "Lähetä" },
	{ fil: "Isumite" },
	{ fj: "Vakauta" },
	{ fr: "Envoyer" },
	{ "fr-CA": "Soumettre" },
	{ ga: "Cuir isteach" },
	{ gu: "મોકલો" },
	{ he: "שלח" },
	{ hi: "जमा करें" },
	{ hr: "Pošaljite" },
	{ ht: "Soumet" },
	{ hu: "Benyújtja" },
	{ id: "Kirim" },
	{ is: "Leggja inn" },
	{ it: "Invia" },
	{ ja: "送信" },
	{ kk: "Жіберу" },
	{ kmr: "Pêşkêş kirin" },
	{ kn: "ಸಲ್ಲಿಸು" },
	{ ko: "전송" },
	{ ku: "ناردن" },
	{ lt: "Pateikti" },
	{ lv: "Iesniegt" },
	{ mg: "Mampifanaraka" },
	{ mi: "Whakaurungia" },
	{ ml: "സമർപ്പിക്കുക" },
	{ mr: "प्रस्तुत करा" },
	{ ms: "Hantar" },
	{ mt: "Jissottomettu" },
	{ mww: "Xa tsab ntawv" },
	{ nb: "Sende" },
	{ nl: "Opslaan" },
	{ or: "ଜମା କରନ୍ତୁ" },
	{ otq: "Pe̲hni" },
	{ pa: "ਸਪੁਰਦ ਕਰੋ" },
	{ pl: "Prześlij" },
	{ prs: "ارسال کردن" },
	{ ps: "وړاندې کړه" },
	{ pt: "Enviar" },
	{ "pt-PT": "Enviar" },
	{ ro: "Prezinte" },
	{ ru: "Отправить" },
	{ sk: "Predložiť" },
	{ sl: "Predloži" },
	{ sm: "Auina Atu" },
	{ "sr-Cyrl": "Прослеђивање" },
	{ "sr-Latn": "Prosleđivanje" },
	{ sv: "Skicka" },
	{ sw: "Wasilisha" },
	{ ta: "சமர்ப்பிக்க" },
	{ te: "సమర్పించు" },
	{ th: "ส่ง" },
	{ "tlh-Latn": "lIy" },
	{ "tlh-Piqd": "" },
	{ to: "ʻAve" },
	{ tr: "Gönder" },
	{ ty: "Hapono" },
	{ uk: "Представити" },
	{ ur: "جمع کروائیں" },
	{ vi: "Gửi" },
	{ yua: "Tuxt a meyaj" },
	{ yue: "提交" },
	{ "zh-Hans": "提交" },
	{ "zh-Hant": "提交" }
];

console.log(
	welcome.map(x => {
		return Object.entries(x)[0][1];
	})
);
